"""Targeted Test Suite for Phase 2: Authoritative AgentResult -> EducationalResponse Integration."""

import pytest
from unittest.mock import MagicMock, patch
from config import Config
from agents.base import AgentResult
from core.synthesis.agent_response_adapter import AgentResponseAdapter, agent_response_adapter
from core.planner.execution_plan import ExecutionPlan


def test_1_no_additional_llm_generation():
    """Test 1: Verify AgentResponseAdapter composes EducationalResponse without invoking any LLM manager or provider."""
    result = AgentResult(
        content="Authoritative answer generated by Orchestrator.",
        confidence=88,
        sources=[{"title": "Doc A", "url": "", "provider": "uploaded_documents", "source_type": "internal_document"}],
        metadata={"response_status": "SUCCESS", "provider": "gemini", "model": "gemini-2.5-flash"},
        success=True,
    )

    with patch("core.llm_manager.LLMManager.generate") as mock_llm_gen:
        edu_resp = agent_response_adapter.compose_from_agent_result(result)
        mock_llm_gen.assert_not_called()
        assert edu_resp["ai_explanation"] == "Authoritative answer generated by Orchestrator."


def test_2_content_identity():
    """Test 2: Verify exact content identity between AgentResult.content and EducationalResponse.ai_explanation (no rewriting)."""
    text = "Exact authoritative response text with special chars & citations [1]."
    result = AgentResult(
        content=text,
        confidence=95,
        sources=[],
        metadata={"response_status": "SUCCESS"},
        success=True,
    )
    edu_resp = agent_response_adapter.compose_from_agent_result(result)
    assert edu_resp["ai_explanation"] == text


def test_3_source_ordering_and_citations():
    """Test 3: Verify source ordering [1] -> source_a, [2] -> source_b, [3] -> source_c in citations payload."""
    sources = [
        {"title": "source_a", "url": "http://a.com", "provider": "tavily", "source_type": "trusted_web", "score": 0.9},
        {"title": "source_b", "url": "http://b.com", "provider": "tavily", "source_type": "trusted_web", "score": 0.8},
        {"title": "source_c", "url": "", "provider": "uploaded_documents", "source_type": "internal_document", "score": 0.95},
    ]
    result = AgentResult(
        content="Test content",
        confidence=90,
        sources=sources,
        metadata={"response_status": "SUCCESS"},
        success=True,
    )
    edu_resp = agent_response_adapter.compose_from_agent_result(result)
    cits = edu_resp["citations"]

    assert len(cits) == 3
    assert cits[0]["id"] == 1 and cits[0]["title"] == "source_a"
    assert cits[1]["id"] == 2 and cits[1]["title"] == "source_b"
    assert cits[2]["id"] == 3 and cits[2]["title"] == "source_c"


def test_4_source_categorization():
    """Test 4: Verify sources are correctly categorized into recognized UI buckets."""
    sources = [
        {"title": "Doc Notes", "provider": "uploaded_documents", "source_type": "internal_document"},
        {"title": "Web Page", "url": "http://web.com", "provider": "tavily", "source_type": "trusted_web"},
        {"title": "Wiki Article", "url": "http://wiki.org", "provider": "wikipedia", "source_type": "wikipedia"},
        {"title": "Paper X", "url": "http://arxiv.org", "provider": "arxiv", "source_type": "semantic_scholar"},
        {"title": "Book Y", "url": "", "provider": "google_books", "source_type": "book"},
        {"title": "Video Z", "url": "http://youtube.com", "provider": "youtube", "source_type": "video"},
    ]
    result = AgentResult(
        content="Test categorization",
        confidence=90,
        sources=sources,
        metadata={"response_status": "SUCCESS"},
        success=True,
    )
    edu_resp = agent_response_adapter.compose_from_agent_result(result)

    assert len(edu_resp["uploaded_notes"]) == 1 and edu_resp["uploaded_notes"][0]["title"] == "Doc Notes"
    assert len(edu_resp["trusted_web"]) == 1 and edu_resp["trusted_web"][0]["title"] == "Web Page"
    assert len(edu_resp["wikipedia"]) == 1 and edu_resp["wikipedia"][0]["title"] == "Wiki Article"
    assert len(edu_resp["research"]) == 1 and edu_resp["research"][0]["title"] == "Paper X"
    assert len(edu_resp["books"]) == 1 and edu_resp["books"][0]["title"] == "Book Y"
    assert len(edu_resp["videos"]) == 1 and edu_resp["videos"][0]["title"] == "Video Z"


def test_5_confidence_preservation():
    """Test 5: Verify adapter preserves AgentResult.confidence when valid."""
    result = AgentResult(
        content="Test confidence",
        confidence=87.5,
        sources=[],
        metadata={"response_status": "SUCCESS"},
        success=True,
    )
    edu_resp = agent_response_adapter.compose_from_agent_result(result)
    assert edu_resp["confidence"] == pytest.approx(0.875, 0.001)


def test_6_insufficient_evidence_status():
    """Test 6: Verify behavior when response_status == INSUFFICIENT_EVIDENCE (no fake categories/sources populated)."""
    insuff_text = "I couldn't find enough information in your indexed documents to create a document-grounded answer."
    result = AgentResult(
        content=insuff_text,
        confidence=0,
        sources=[{"title": "Stale Source", "url": "", "provider": "uploaded_documents"}],
        metadata={"response_status": "INSUFFICIENT_EVIDENCE", "failure_reason": "INSUFFICIENT_EVIDENCE"},
        success=False,
    )
    edu_resp = agent_response_adapter.compose_from_agent_result(result)

    assert edu_resp["ai_explanation"] == insuff_text
    assert edu_resp["response_status"] == "INSUFFICIENT_EVIDENCE"
    assert len(edu_resp["citations"]) == 0
    assert len(edu_resp["uploaded_notes"]) == 0
    assert len(edu_resp["trusted_web"]) == 0
    assert "Insufficient document evidence" in edu_resp["learning_summary"]


def test_7_error_status():
    """Test 7: Verify behavior when response_status == ERROR."""
    err_text = "The AI generation service is temporarily unavailable."
    result = AgentResult(
        content=err_text,
        confidence=0,
        sources=[],
        metadata={"response_status": "ERROR"},
        success=False,
        error="LLM timeout",
    )
    edu_resp = agent_response_adapter.compose_from_agent_result(result)

    assert edu_resp["ai_explanation"] == err_text
    assert edu_resp["response_status"] == "ERROR"
    assert len(edu_resp["citations"]) == 0
    assert "Execution error occurred" in edu_resp["learning_summary"]


def test_8_legacy_full_graph_compatibility():
    """Test 8: Verify legacy execution_mode="full" still permits existing KnowledgeSynthesizer -> ResponseComposer behavior."""
    from graph.nodes.synthesis_node import knowledge_synthesis_node
    from graph.state import EKIPGraphState

    state = EKIPGraphState(
        question="What is quantum computing?",
        execution_mode="full",
        skip_synthesis=False,
        provider_metadata={
            "verified_collection": {
                "query": "What is quantum computing?",
                "verified_results": [],
                "overall_confidence": 0.9,
                "overall_agreement": 0.9,
                "verification_summary": "Verified",
            }
        }
    )

    with patch("core.synthesis.knowledge_synthesizer.synthesize") as mock_synth, \
         patch("core.synthesis.response_composer.compose_response") as mock_comp:

        mock_synth.return_value = MagicMock()
        mock_comp_resp = MagicMock()
        mock_comp_resp.dict.return_value = {"ai_explanation": "Legacy full graph response"}
        mock_comp_resp.learning_summary = "Legacy summary"
        mock_comp_resp.providers_used = ["gemini"]
        mock_comp_resp.confidence = 0.9
        mock_comp.return_value = mock_comp_resp

        updated_state = knowledge_synthesis_node(state)
        mock_synth.assert_called_once()
        mock_comp.assert_called_once()
        assert updated_state.educational_response == {"ai_explanation": "Legacy full graph response"}
