"""Targeted Test Suite for Phase 1: Single Authoritative Answer Generation & Duplicate Synthesis Prevention."""

import pytest
from unittest.mock import MagicMock, patch
from config import Config
from agents.orchestrator import OrchestratorAgent
from agents.base import AgentResult
from graph.builder import create_ekip_planning_graph
from graph.state import EKIPGraphState


class DummyEngine:
    def __init__(self, has_docs=True):
        self.has_docs = has_docs
        self.doc_count = 5 if has_docs else 0
        self.cfg = type("Cfg", (), {"RERANK_TOP_K": 5})()

    def list_docs(self):
        return {"quantum_notes.pdf": {"chunks": 5, "pages": 2}} if self.has_docs else {}

    def dense_search(self, query, k=8, **kwargs):
        return []

    def sparse_search(self, query, k=8, **kwargs):
        return []

    def reciprocal_rank_fusion(self, dense, sparse):
        return []

    def rerank(self, query, fused, top_k=5):
        return []

    def compress_context(self, reranked, max_chunks=6):
        return []


class DummyMemory:
    def record_query_metrics(self, **kwargs):
        pass


def test_planning_graph_in_chat_planning_mode_skips_knowledge_synthesizer():
    """Verify that planning_graph.invoke in chat_planning mode skips KnowledgeSynthesizer and EducationalResponse creation."""
    graph = create_ekip_planning_graph()
    prompt = "Explain quantum computing fundamentals."

    with patch("core.orchestrator.knowledge_orchestrator.collect") as mock_col, \
         patch("core.synthesis.knowledge_synthesizer.synthesize") as mock_synth:
        mock_col.return_value = MagicMock(results=[], sources_completed=[], sources_failed=[], total_latency_ms=0, dict=lambda: {})
        plan_state = graph.invoke({
            "question": prompt,
            "conversation_history": [],
            "execution_mode": "chat_planning",
            "skip_synthesis": True,
        })

        # KnowledgeSynthesizer MUST NOT be invoked
        mock_synth.assert_not_called()

        # Planning outputs MUST be populated
        assert plan_state.execution_plan is not None
        assert plan_state.intent is not None
        assert plan_state.difficulty is not None
        assert plan_state.source_strategy is not None

        # Educational response MUST be None (no duplicate answer pre-generated)
        assert plan_state.educational_response is None
        assert any("Skipped" in r for r in plan_state.planner_reasoning)


def test_orchestrator_is_authoritative_when_synthesis_skipped_in_graph():
    """Verify that when synthesis is skipped in graph, OrchestratorAgent executes its own authoritative synthesis pipeline."""
    graph = create_ekip_planning_graph()
    prompt = "Explain the solar system structure."

    with patch("core.orchestrator.knowledge_orchestrator.collect") as mock_col:
        mock_col.return_value = MagicMock(results=[], sources_completed=[], sources_failed=[], total_latency_ms=0, dict=lambda: {})
        plan_state = graph.invoke({
            "question": prompt,
            "conversation_history": [],
            "execution_mode": "chat_planning",
            "skip_synthesis": True,
        })

    engine = DummyEngine(has_docs=False)
    memory = DummyMemory()
    orch = OrchestratorAgent(Config, engine, memory)

    # Mock Orchestrator's internal synthesis runner to return a known authoritative response
    authoritative_result = AgentResult(
        content="Authoritative answer generated by OrchestratorAgent.",
        confidence=90,
        sources=[],
        metadata={"provider": "mock", "model": "mock-model"},
        success=True,
    )
    orch._synthesize = MagicMock(return_value=authoritative_result)

    ctx = {
        "query": prompt,
        "history": [],
        "execution_plan": plan_state.execution_plan,
        "plan_state": plan_state,
    }

    result = orch.run(ctx)

    # Orchestrator._synthesize MUST be called as the single authoritative answer path
    orch._synthesize.assert_called_once()
    assert result.content == "Authoritative answer generated by OrchestratorAgent."
    assert result.success is True


def test_full_graph_mode_preserves_legacy_synthesis_behavior():
    """Verify that legacy/full graph execution mode still executes knowledge_synthesis_node when verified_collection exists."""
    from graph.nodes.synthesis_node import knowledge_synthesis_node

    state = EKIPGraphState(
        question="What is deep learning?",
        execution_mode="full",
        skip_synthesis=False,
        provider_metadata={
            "verified_collection": {
                "query": "What is deep learning?",
                "verified_results": [],
                "overall_confidence": 0.9,
                "overall_agreement": 0.9,
                "verification_summary": "Verified",
            }
        }
    )

    with patch("core.synthesis.knowledge_synthesizer.synthesize") as mock_synth, \
         patch("core.synthesis.response_composer.compose_response") as mock_comp:

        mock_synth.return_value = MagicMock()
        mock_comp_resp = MagicMock()
        mock_comp_resp.dict.return_value = {"ai_explanation": "Full mode explanation."}
        mock_comp_resp.learning_summary = "Summary"
        mock_comp_resp.providers_used = ["gemini"]
        mock_comp_resp.confidence = 0.9
        mock_comp.return_value = mock_comp_resp

        updated_state = knowledge_synthesis_node(state)

        # In full mode with verified collection, synthesis MUST execute
        mock_synth.assert_called_once()
        mock_comp.assert_called_once()
        assert updated_state.educational_response == {"ai_explanation": "Full mode explanation."}
