"""EKIP ExecutionPlan Domain Model for Phase 2.3+ Agentic Execution Contract."""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from core.models.domain import SourceType
from core.planner.enums import (
    EducationalIntent,
    DifficultyLevel,
    SourceStrategy,
    RetrievalStrategy,
    ExpectedOutputFormat,
    LatencyEstimate,
    CostEstimate,
    DocumentUsageMode,
)


class ExecutionPlan(BaseModel):
    """Structured execution contract generated by Knowledge Planner for downstream retrieval agents."""

    intent: EducationalIntent = Field(default=EducationalIntent.CONCEPT_EXPLANATION)
    secondary_intents: List[EducationalIntent] = Field(default_factory=list, description="Additional secondary educational intents for compound queries")
    difficulty: DifficultyLevel = Field(default=DifficultyLevel.INTERMEDIATE)
    source_strategy: SourceStrategy = Field(default=SourceStrategy.GENERAL_KNOWLEDGE)
    document_usage_mode: DocumentUsageMode = Field(default=DocumentUsageMode.EXCLUDED)
    selected_sources: List[SourceType] = Field(default_factory=list)
    retrieval_strategy: RetrievalStrategy = Field(default=RetrievalStrategy.HYBRID)
    expected_output: ExpectedOutputFormat = Field(default=ExpectedOutputFormat.DETAILED_EXPLANATION)
    estimated_latency: LatencyEstimate = Field(default=LatencyEstimate.MEDIUM)
    estimated_cost: CostEstimate = Field(default=CostEstimate.LOW)

    reasoning: str = Field(default="", description="Explainable reasoning for planner decisions")
    reasoning_steps: List[str] = Field(default_factory=list, description="Step-by-step breakdown of decisions")

    # Resource requirements flags
    requires_internal_documents: bool = Field(default=False)
    requires_external_search: bool = Field(default=False)
    requires_research: bool = Field(default=False)
    requires_books: bool = Field(default=False)
    requires_videos: bool = Field(default=False)
    requires_code: bool = Field(default=False)

    target_documents: List[str] = Field(default_factory=list, description="Target document filenames if specified or resolved")

    metadata: Dict[str, Any] = Field(default_factory=dict)

